.TH UPDATE-NFONTS 1 "November 25, 2004"
.SH NAME
update-nfonts \- create nfonts from the systemfonts using symlinks
.SH SYNOPSIS
.B update-nfonts
.SH DESCRIPTION
This manual page documents briefly the
.B update-nfonts
command.
This manual page was written for the Debian distribution
because the original program does not have a manual page.
.PP
\fBupdate-nfonts\fP is a wrapper script around mknfonts.
.SH SEE ALSO
.BR GNUstep (7).
.SH AUTHOR
This manual page was written by G\[:u]rkan Seng\[:u]n <gurkan@linuks.mine.nu>,
for the Debian project (but may be used by others).
